ColinBertin/traq

config/routes.rb

Routes created.
Need to be check and validate by TA.

added the routes

---

app/assets/stylesheets/config/_bootstrap_variables.scss

Changed the color values of bootstrap

changed color variables

---

app/assets/config/manifest.js

added //= link application.css

bootstrap change

---

app/controllers/locations_controller.rb
app/policies/location_policy.rb
app/views/locations/edit.html.erb
app/views/locations/index.html.erb
app/views/locations/new.html.erb
app/views/locations/show.html.erb
test/controllers/locations_controller_test.rb
test/policies/location_policy_test.rb

location controller, view and pundit setup

location controller setup

---

Gemfile
app/models/location.rb

beautyfier solve + destroy depend

Htmlbeauty

---

app/controllers/comments_controller.rb
app/controllers/locations_controller.rb
app/policies/comment_policy.rb
app/views/locations/show.html.erb
test/controllers/comments_controller_test.rb
test/policies/comment_policy_test.rb

please help with index so page will show after comment

Commentcontroller

---

app/controllers/contributions_controller.rb
app/controllers/locations_controller.rb
app/policies/contribution_policy.rb
app/views/contributions/edit.html.erb
app/views/contributions/index.html.erb
app/views/contributions/new.html.erb
app/views/locations/show.html.erb
test/controllers/contributions_controller_test.rb
test/policies/contribution_policy_test.rb

contribution controller done 
Need to add the contribution to the location show page

Contribution c

---

app/controllers/comments_controller.rb
app/controllers/locations_controller.rb
app/policies/comment_policy.rb
app/views/locations/show.html.erb

controllers 'done' for the moment

controllers done

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_home.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_input.scss
app/assets/stylesheets/components/_text.scss
app/views/contributions/new.html.erb
app/views/locations/_card.html.erb
app/views/locations/index.html.erb
app/views/locations/show.html.erb

updated css in location, contribution,fixed the style in comment

---

app/views/locations/new.html.erb

deleted the f.tag in new 'location'

deleted tags

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_home.scss
app/views/locations/show.html.erb

Contribution card design. edits to SCSS files

css card design

---

app/assets/stylesheets/components/_home.scss

added margin bottom for all pages

---

app/views/shared/_bottom_navbar.erb
app/views/users/contributions/index.html.erb

user's contributions page

---

app/views/locations/index.html.erb
app/views/locations/show.html.erb
db/seeds.rb

added more location on seeds

---

app/views/locations/index.html.erb
app/views/locations/show.html.erb

map box design

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_home.scss
app/views/locations/_card.html.erb
app/views/pages/home.html.erb

landing page edit
card on the index for locations

added card design in the location and edited a bit on the homepage

---

app/controllers/locations_controller.rb
app/javascript/controllers/mapbox_controller.js
app/views/locations/index.html.erb
app/views/locations/show.html.erb

fixing user icon path in mapbox controller

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_home.scss
app/assets/stylesheets/components/_navbar.scss
app/views/locations/_card.html.erb
app/views/locations/new.html.erb
app/views/shared/_navbar_shared.html.erb

fixed issue for position of bottom and top bar on mobile browser
changed font size on the cards location/show and locations/index

bottom and top bar. fixed being fixed in position

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_home.scss
app/controllers/contributions_controller.rb
app/policies/contribution_policy.rb
app/policies/user/contribution_policy.rb
app/views/contributions/edit.html.erb
app/views/locations/_card.html.erb
app/views/locations/show.html.erb
app/views/users/contributions/index.html.erb

- new design on the update contribution page (temporary button link)
-  new pundit policy for editing contributions
- added new action for the update on the contributions controller

Design contribution page

---

app/assets/stylesheets/components/_home.scss
app/views/layouts/application.html.erb
app/views/locations/_card.html.erb
app/views/shared/_navbar_shared.html.erb

navbar update fixed
- still fixing the margin of the top part but the rest are okay so far
- will add icons to the specific shelter later

changes on the navbar top

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_home.scss
app/models/contribution.rb
app/views/contributions/new.html.erb
app/views/locations/_card.html.erb
app/views/locations/_contribution_card.html.erb
app/views/locations/edit.html.erb
app/views/users/contributions/_contribution_card.html.erb
app/views/users/contributions/index.html.erb
db/migrate/20220309065255_change_supply_type_to_int.rb
db/schema.rb

updated the card design for location and made dome DRY coding
will be copy pasting the it to the show with the icon (will work on it tonight with updated seed)
added a new migration file for updating the t:string of supply_type to t:integer
DB MIGRATE to be updated

worked on the card design for the supplies available

---

app/assets/stylesheets/components/_home.scss
app/controllers/contributions_controller.rb
app/policies/contribution_policy.rb
app/views/users/contributions/_contribution_card.html.erb

delete function working as user wgho contributed

added delete contribution function works fine with pundit

---

app/controllers/application_controller.rb
app/helpers/meta_tags_helper.rb
app/views/layouts/application.html.erb
config/initializers/default_meta.rb
config/meta.yml
public/404.html
public/422.html
public/500.html

Error page

---

app/views/locations/_info_window.html.erb
app/views/locations/show.html.erb

Adding supply type and number of people in shelter on popup card
Fixing minor issues

Checkin iss

---

app/controllers/users/locations_controller.rb
app/policies/user/location_policy.rb
app/views/shared/_bottom_navbar.erb
app/views/users/contributions/index.html.erb
app/views/users/locations/_location_card.html.erb
app/views/users/locations/index.html.erb
config/routes.rb
test/controllers/users/locations_controller_test.rb

Adding user/locations routes, index pages

adding my locations pages

---

Gemfile
Gemfile.lock
app/javascript/controllers/checkin_controller.js
app/models/user.rb
app/views/locations/show.html.erb
db/migrate/20220310073539_add_tel_to_locations.rb
db/migrate/20220310074253_fix_column_name.rb
db/migrate/20220310080802_remove_tel.rb
db/schema.rb
db/seeds.rb

Revert "Notice board"

---

app/assets/stylesheets/components/_home.scss
app/views/pages/home.html.erb
app/views/users/contributions/index.html.erb
app/views/users/locations/_location_card.html.erb
app/views/users/locations/index.html.erb

added H1 text on index for user contribution and location
updated tagline on the homepage
updated the edit delete and add text button to shorter text

Design check 01

---

app/views/locations/new.html.erb
app/views/locations/show.html.erb
app/views/pages/home.html.erb
app/views/shared/_modal.html.erb

- fixed no supply available in the shelter to grey card
- changed the edit location button for user/owner to an icon
- took out the icons of the shelter when new NGO location points are made
- fixed the card design when supplies are available

card supply info changes
